{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12541126","self":"https://issues.apache.org/jira/rest/api/latest/issue/12541126","key":"DERBY-5601","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/3","id":"3","description":"The problem is a duplicate of an existing issue.","name":"Duplicate"},"customfield_12310220":"2012-02-08 08:50:37.656","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"226478","customfield_12310222":"1_*:*_1_*:*_1133180341_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2012-02-16T23:05:21.732+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5601/watchers","watchCount":1,"isWatching":false},"created":"2012-02-03T20:19:01.481+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/1","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/blocker.png","name":"Blocker","id":"1"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"2.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12316344","id":"12316344","description":"First release on the 10.9 branch","name":"10.9.1.0","archived":false,"released":true,"releaseDate":"2012-06-25"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12348021","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12348021","type":{"id":"12310010","name":"Incorporates","inward":"is part of","outward":"incorporates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310010"},"outwardIssue":{"id":"12541864","key":"DERBY-5607","self":"https://issues.apache.org/jira/rest/api/2/issue/12541864","fields":{"summary":"Deadlock in Java 5 VM when using NATIVE authentication with a client running in the same VM as the server","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/2","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/critical.png","name":"Critical","id":"2"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12348215","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12348215","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12476715","key":"DERBY-4836","self":"https://issues.apache.org/jira/rest/api/2/issue/12476715","fields":{"summary":"many failures with IBM 1.5 and 1.6 on windows after test InternationalConnectTest","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12348214","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12348214","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12541869","key":"DERBY-5608","self":"https://issues.apache.org/jira/rest/api/2/issue/12541869","fields":{"summary":"BaseTestCase.readProcessOutput should read getInputStream()  and getErrorStream() in separate threads","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}}],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2013-06-17T09:19:43.324+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11415","id":"11415","name":"Services"},{"self":"https://issues.apache.org/jira/rest/api/2/component/11413","id":"11413","name":"Test"}],"timeoriginalestimate":null,"description":"The IBM Windows runs on trunk  have been hanging  in NativeAuthenticationServiceTest.  This is preventing tests from continuing or being posted. The actual test run hangs at :\r\n....\r\nemb)lang.AutoIncrementTest.test_4437_03_deferredInsert used 218 ms .\r\n(emb)lang.HalfCreatedDatabaseTest.test_4589 used 6859 ms .\r\n(emb)lang.HalfCreatedDatabaseTest.test_5526 used 16 ms .\r\n(emb)lang.NativeAuthenticationServiceTest.testAll used 24061 ms .\r\n(emb)lang.NativeAuthenticationServiceTest.testAll used 17781 ms .\r\n(emb)lang.NativeAuthenticationServiceTest.testAll used 11187 ms .\r\n(net)lang.NativeAuthenticationServiceTest.testAll used 18187 ms .\r\n(net)lang.NativeAuthenticationServiceTest.testAll \r\n\r\nand so no test continue and no results get posted to:\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-1239981.html\r\n\r\nThe last run where this did not happen was:\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testSummary-1236968.html\r\n\r\n\r\nThe actual command being executed is:\r\n       1  4748  2676  0 20:23:24 CONIN$ 46:30 C:\\WINDOWS\\system32\\java.exe -Dder\r\nbyTesting.ldapServer=socket.usca.ibm.com -DderbyTesting.ldapPort=389 -DderbyTest\r\ning.dnString=oakland.ibm.com -DderbyTesting.ldapUser=mamta -DderbyTesting.ldapPa\r\nssword=xxxxx  -Xmx512M -Dderby.tests.networkServerStartTimeout=480 -Dderby.te\r\nsts.basePort=3100 -Dderby.tests.trace=true -DderbyTesting.oldReleasePath=d:/jart\r\nest/releases_for_upgrade_tests junit.textui.TestRunner org.apache.derbyTesting.f\r\nunctionTests.suites.All\r\n\r\nI couldn't reproduce this running the single test on my machine.  Marking this blocker as the Oracle Nightlies seem to be having serious issues too that date back further.\r\nhttp://dbtg.foundry.sun.com/derby/test/Daily/jvm1.6/testing/Limited/\r\n\r\n\r\nRight now we have no reliable regression testing going on.\r\n\r\n\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10369","value":"Regression Test Failure","id":"10369"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"36032","summary":"Windows hang in NativeAuthenticationServiceTest testAll with prior interrupt error in SecureServerTest and other cascade errors and failures","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":null,"customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":31,"total":31,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13200098","id":"13200098","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Temporarily disabled the test to see if we can get tests running again. Dag reports infrastructure problems in the Oracle runs. There have been simultaneous infrastructure changes in the IBM recently which confused me thinking that was the reason, but clearly it is this test that has consistently been hanging since the Monday Jan 30, 1238138 run.\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-02-03T22:14:47.418+0000","updated":"2012-02-03T22:14:47.418+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13201484","id":"13201484","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Posted this info on the list, but putting here to keep history in Jira.  Myrna is investigating why cygwin upgrade may have caused this issue.\r\n\r\nTalking with Myrna, Mike and Mamta and looking back at the onset of the NativeAuthenticationTest hang.  I see that even at that time we had the prior SecureServerTest failure\r\n\r\n(net)derbynet.SecureServerTest.testServerStartup used 6750 ms E.\r\n(net)derbynet.SecureServerTest.testServerStartup used 46827 ms F.\r\nWhich we found later to have the stack Trace below [1] and which seemed to send things going down hill and led up to the hang, so may be related.\r\nMyrna also told me at the  the time this all started, she just switched over to cygwin from another shell program.\r\n\r\nI have done suites.All runs sane and insane on my Windows machine as have Mike and Mamta and runs are clean, so I think it would be good to reenable NativeAuthenticationServiceTest on non-windows platforms and even on windows for non-ibm jvm's.\r\nMyrna is working on figuring out why the cygwin upgrade caused such trouble on this machine.  I will do this tomorrow unless someone else beats me to it.\r\n\r\n\r\nThanks\r\n\r\nKathey\r\n\r\n[1] SecureServerTest( Opened = false, Authenticated= false, CustomDerbyProperties= null, WildCardHost= null )java.lang.InterruptedException\r\n\tat org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:184)\r\n\tat org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:146)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runServerCommand(SecureServerTest.java:481)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runsysinfo(SecureServerTest.java:411)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:350)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:116)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-02-06T19:17:58.353+0000","updated":"2012-02-06T19:17:58.353+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13202506","id":"13202506","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Much conversation on this issue is occurring on the derby-dev list on the thread [URGENT] Critical test situation on trunk\r\nhttp://old.nabble.com/-URGENT--Critical-test-situation-on-trunk-td33259629.html\r\n\r\nAlso changed summary to include prior errors/failures leading up to the hang\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-02-07T16:23:04.689+0000","updated":"2012-02-07T16:23:04.689+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13203384","id":"13203384","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I used various old saved builds of derby and found the problem starts happening with builds including revision 1159337 (http://svn.apache.org/viewvc?view=revision&revision=1159337), and not before. \r\n\r\nI also ran with Kristian's patch, which gives some output to the console:\r\n(net)derbynet.SecureServerTest.testServerStartup START-SPAWNED:[-Demma.verbosity.level=silent, org.apache.derby.drda.NetworkServerControl, -p, 1527, sysinfo] STANDARD OUTPUT: exit code=-1\r\n--------- Derby Network Server Information --------\r\nVersion: CSS10090/10.9.0.0 alpha - (1241655M)  Build: 1241655M  DRDA Product Id: CSS10090\r\nderby.drda.maxThreads=0\r\nderby.drda.sslMode=off\r\nderby.drda.keepAlive=true\r\nderby.drda.minThreads=0\r\nderby.drda.portNumber=1527\r\nderby.drda.logConnections=false\r\nderby.drda.timeSlice=0\r\nderby.drda.startNetworkServer=false\r\nderby.drda.host=localhost\r\nderby.drda.traceAll=false\r\n[sysinfo output for revision 10.9.0.0 alpha - (1241655M)] \r\nEND-SPAWNED  :[-Demma.verbosity.level=silent, org.apache.derby.drda.NetworkServerControl, -p, 1527, sysinfo] STANDARD OUTPUT:\r\nused 5437 ms E.\r\n(net)derbynet.SecureServerTest.testServerStartup used 13875 ms F.\r\n\r\n(Soon) after this, I killed the java process\r\n\r\nIn the fail directory, this is the error stack:\r\n[Error/failure logged at Tue Feb 07 16:02:19 PST 2012]\r\njava.lang.InterruptedException: process exited with code 0\r\n\tat org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:234)\r\n\tat org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:150)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runServerCommand(SecureServerTest.java:481)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runsysinfo(SecureServerTest.java:411)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:350)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat java.lang.reflect.Method.invoke(Method.java:600)\r\n\tat junit.framework.TestCase.runTest(TestCase.java:164)\r\n\tat junit.framework.TestCase.runBare(TestCase.java:130)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:116)\r\n\tat junit.framework.TestResult$1.protect(TestResult.java:106)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.framework.TestResult.run(TestResult.java:109)\r\n\tat junit.framework.TestCase.run(TestCase.java:120)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n\tat junit.textui.TestRunner.start(TestRunner.java:185)\r\n\tat junit.textui.TestRunner.main(TestRunner.java:143)\r\n\r\n[Error/failure logged at Tue Feb 07 16:02:37 PST 2012]\r\njunit.framework.AssertionFailedError: directory trace does not exist\r\n\tat junit.framework.Assert.fail(Assert.java:47)\r\n\tat junit.framework.Assert.assertTrue(Assert.java:20)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.setTraceDirectory(SecureServerTest.java:382)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:352)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat java.lang.reflect.Method.invoke(Method.java:600)\r\n\tat junit.framework.TestCase.runTest(TestCase.java:164)\r\n\tat junit.framework.TestCase.runBare(TestCase.java:130)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:116)\r\n\tat junit.framework.TestResult$1.protect(TestResult.java:106)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.framework.TestResult.run(TestResult.java:109)\r\n\tat junit.framework.TestCase.run(TestCase.java:120)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n\tat junit.textui.TestRunner.start(TestRunner.java:185)\r\n\tat junit.textui.TestRunner.main(TestRunner.java:143)\r\n\r\nderby.log is unexiting - just boots and shutdowns and stacks of \r\njava.sql.SQLException: Database 'singleUse/oneuse0' not found.\r\nand \r\njava.sql.SQLException: Database 'testbase' not found.\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-08T08:50:37.656+0000","updated":"2012-02-08T08:50:37.656+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13203474","id":"13203474","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Thanks for running the test again, Myrna.\r\n\r\nI don't see anything in the output explaining the problem though.\r\nThe printing of stdout tells that the interrupt did happen (exit code = -1), but after the output has been read the process reports that it exited normally (exit code = 0).\r\n\r\nI think there may be a few issues with the code in SpawnedProcess; it doesn't seem to explicitly close the process streams, waitFor may hang forever, and more importantly, it doesn't reset the interrupt flag. The latter may be what's causing the cascade error/failures.\r\nI'll write a patch for testing on the machine experiencing this issue.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-08T11:06:58.699+0000","updated":"2012-02-08T11:06:58.699+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13204059","id":"13204059","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I have been remiss - I did not pay proper attention to failures.\r\nOn the machine where I'm seeing trouble, with 10.8.2.2 and 10.9 alpha versions before revision 1159337, the suites.All fails *before* SecureServerTest: test_01_WrongUsage used 10969 ms E. \r\nThis is in test derbynet.NetworkServerControlApiTest. \r\nThe stack trace from the fail directory is similar to the interrupt error reported before: \r\n--------------------------- \r\n[Error/failure logged at Wed Feb 08 13:46:35 PST 2012]\r\njava.lang.InterruptedException\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.readProcessOutput(BaseTestCase.java:763)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.assertExecJavaCmdAsExpected(BaseTestCase.java:507)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.NetworkServerControlApiTest.test_01_WrongUsage(NetworkServerControlApiTest.java:91)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat java.lang.reflect.Method.invoke(Method.java:600)\r\n\tat junit.framework.TestCase.runTest(TestCase.java:164)\r\n\tat junit.framework.TestCase.runBare(TestCase.java:130)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)\r\n\tat junit.framework.TestResult$1.protect(TestResult.java:106)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.framework.TestResult.run(TestResult.java:109)\r\n\tat junit.framework.TestCase.run(TestCase.java:120)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n\tat junit.textui.TestRunner.start(TestRunner.java:185)\r\n\tat junit.textui.TestRunner.main(TestRunner.java:143)\r\n--------------------------- \r\nSo looks like this will happen at some point on a fast machine. Perhaps the check in of 1159337 improved matters, but didn't fix? \r\nMyrna","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-08T22:22:52.465+0000","updated":"2012-02-08T22:22:52.465+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13204826","id":"13204826","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"I have set up an XP guest os under Virtual Box on my laptop. I have successfully run NativeAuthenticationServiceTest using the Windows versions of Java 5 and Java 6 from Oracle. The test did not hang for me. I ran the test against the state of the trunk after checking in the fix for DERBY-5607. It would be interesting to know if NativeAuthenticationServiceTest still hangs for you on your platform. Thanks.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2012-02-09T20:32:07.948+0000","updated":"2012-02-09T20:32:07.948+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205532","id":"13205532","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Rick, I ran with a recent build (including Christian's interrupt flag reset for DERBY-5608) but with the NativeAuthenticationServiceTest re-enabled for windows and found no hang. It looks like the hang is gone, and the test can be re-enabled.\r\n\r\nI still see a multitude of failures though, so this issue cannot yet be closed.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-10T16:38:36.302+0000","updated":"2012-02-10T16:38:36.302+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205553","id":"13205553","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"> I still see a multitude of failures though, so this issue cannot yet be closed.\r\n\r\nIs it as bad as before, or is it somewhat better?\r\nThe hope was that those caused by shutdown errors would go away with the fix.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-10T17:01:55.290+0000","updated":"2012-02-10T17:01:55.290+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205561","id":"13205561","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Unfortunately, and puzzlingly, it's exactly the same (except for more tests run because I re-activated NativeAuthenticationServiceTest for this run).\r\nI'm getting this behavior with just running:\r\n   java -Dderby.tests.trace=true junit.textui.TestRunner org.apache.derbyTesting.functionTests.suites.All > outfile.out 2>&1\r\n\r\nHere's the interrupt exception with this latest run:\r\n-------------------\r\n1) test_01_WrongUsage(org.apache.derbyTesting.functionTests.tests.derbynet.NetworkServerControlApiTest)java.lang.InterruptedException\r\n\tat java.lang.ProcessImpl.waitFor(Native Method)\r\n\tat org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:215)\r\n\tat org.apache.derbyTesting.junit.SpawnedProcess.complete(SpawnedProcess.java:176)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.readProcessOutput(BaseTestCase.java:774)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.assertExecJavaCmdAsExpected(BaseTestCase.java:508)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.NetworkServerControlApiTest.test_01_WrongUsage(NetworkServerControlApiTest.java:81)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n----------------------------\r\nand the second and third failures are just as before. \r\n\r\nNote that the interrupt error does occur now in a different test than when we first saw this.\r\n\r\nIt's still not happening when I run the derbynet._Suite by itself, only when running suites.All.\r\nI'll do the following experiments over the weekend:\r\n- run without the redirect to file 2>&1 (perhaps there's a problem lobbing stdout and stderr together?)\r\n- run in a dos command shell\r\n- get a smaller suites.All subset\r\n- install a debugger and step through? (Probably won't get to this until Monday).\r\n\r\nAny other suggestions on what I could do to gather more information?\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-10T17:25:41.864+0000","updated":"2012-02-10T17:25:41.864+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205590","id":"13205590","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"could you post the suites output of your current fail (just up and a little past the first failure is enough to get an idea of what tests are involved).  If it is as before then the first error happens very quickly (i think you said 2-3 minutes), and less than 50 fixtures.  \r\n\r\nI think best next step is just do binary search to narrow down tests run by suite.all, hopefully eliminating most tests before the failure and still\r\ncoming up with reproducible case in your environment.  At this point it seems like some test before the failing test is causing the issue, so narrowing down list of suspects would help.  ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-02-10T18:12:02.857+0000","updated":"2012-02-10T18:12:02.857+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205601","id":"13205601","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"I agree with Mike.\r\n\r\nYou could also move derbynet to the end of the run and see if it still happens then.\r\nAnother theory is that due to the interrupt the subprocess doesn't terminate and interferes with the tests. I'll have a patch for that soon...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-10T18:21:36.969+0000","updated":"2012-02-10T18:21:36.969+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205787","id":"13205787","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I'm attaching the console output from one of the failed runs (this one included Kristian's latest patch, and a modified lang._Suite so it ran NativeAuthenticationServiceTest).\r\n\r\nThe test run on this machine with just DOS failed in the same test (NetworkServerControlAPITest.test_01_WrongUsage)","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-10T21:56:38.275+0000","updated":"2012-02-10T21:56:38.275+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205790","id":"13205790","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Forgot to mention; in the saved console output file I removed all failures and errors > 50, so there's stack traces of 50 errors and 50 failures.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-10T21:58:01.887+0000","updated":"2012-02-10T21:58:01.887+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205859","id":"13205859","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"I wonder if it would be helpful to print \r\nSystem.out.println(\"isInterrupted() value: \" + Thread.currentThread().isInterrupted() );\r\n\r\nin BaseTestCase.runBare()\r\n\r\nI think that method is invoked for each test.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-02-10T23:25:11.939+0000","updated":"2012-02-10T23:25:11.939+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13205942","id":"13205942","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dagw","name":"dagw","emailAddress":"dag dot wanvik at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=dagw&avatarId=16789","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=dagw&avatarId=16789","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=dagw&avatarId=16789","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=dagw&avatarId=16789"},"displayName":"Dag H. Wanvik","active":true},"body":"May not be relevant at all, but Derby does use interrupts itself in NetworkServerControlImpl in three places.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dagw","name":"dagw","emailAddress":"dag dot wanvik at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=dagw&avatarId=16789","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=dagw&avatarId=16789","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=dagw&avatarId=16789","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=dagw&avatarId=16789"},"displayName":"Dag H. Wanvik","active":true},"created":"2012-02-11T01:00:39.486+0000","updated":"2012-02-11T01:00:39.486+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13206721","id":"13206721","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Attaching an extended version of SpawnedProcess, which isn't suspectible to interrupts when waiting for the process to complete.\r\n\r\nI've let the uses of SpawnedProcess.complete behave as earlier, so if the interrupt seen earlier stopped us from waiting/destroying a process the test may now hang for 45 minutes before killing the process. For testing purposes you can set this to a lower value (use milliseconds) with derby.tests.process.killThreshold. This value must be higher than the time it takes to run the longest test using an external process, otherwise the process will be terminated prematurely. On a hang you should be able to use jstack to see where the code is waiting/stuck.\r\n\r\nI've run suites.All with the patch on Windows Vista without errors, but there were no process-related issues in that run anyway.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-13T07:09:19.851+0000","updated":"2012-02-13T07:09:19.851+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207155","id":"13207155","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I appreciate all the effort put into this issue...\r\n\r\nUnfortunately, I cannot build after installing the latest patch, I get:\r\n\r\n    [javac] C:\\derby\\trunk\\java\\testing\\org\\apache\\derbyTesting\\junit\\SpawnedProcess.java:23: cannot find symbol\r\n    [javac] import java.io.Closeable;\r\n    [javac]               ^\r\n    [javac]   symbol:   class Closeable\r\n    [javac]   location: package java.io\r\n    [javac] C:\\derbyt\\trunk\\java\\testing\\org\\apache\\derbyTesting\\junit\\SpawnedProcess.java:381: cannot find symbol\r\n    [javac]     private void closeStream(Closeable stream) {\r\n    [javac]                              ^\r\n    [javac]   symbol:   class Closeable\r\n    [javac]   location: class SpawnedProcess\r\n    [javac] 2 errors\r\n    [javac] Compile failed; see the compiler error output for details.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-13T20:06:46.122+0000","updated":"2012-02-13T20:06:46.122+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207223","id":"13207223","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"it built for me in a client using ibm16 in my path and ANT_JAVA set to jdk16, with nothing in my local.properties (most notably no jdk4lib* variable settings).  Closable looks like it was introduced in 1.5, so probably will not compile when using a pre\r\n1.5 compiler or compiler directive.  I think there is some magic that needs to be put into directories that require higher than 1.5 to build.  If I add the\r\njdk14* lib settings to my local.properties I see the errors Myrna reports.\r\n\r\nI think this means that if we check the patch in that j2me based jvms no longer will be able to run tests that use SpawnedProcess.  And if we check it\r\nin, probably needs a change to the build.xml file in the junit directory indicating that it need jdk15 libs for that file.  ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-02-13T21:26:01.814+0000","updated":"2012-02-13T22:12:51.472+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207277","id":"13207277","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I revised my properties and was able to get this to build...\r\n\r\nI'll try out the patch and post the results.\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-13T22:24:00.323+0000","updated":"2012-02-13T22:24:00.323+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207290","id":"13207290","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Although I don't enjoy being stuck in the past, it wasn't my intension to break the J2ME support :)\r\nI first thought my IDE had fooled me, but it turns out that it was because PropertySetter has been simplified. After that happened I have not manually configured my build system to catch these issues.\r\n\r\nI've attached a new verrsion of the patch.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-13T22:35:42.382+0000","updated":"2012-02-13T22:35:42.382+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207392","id":"13207392","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"The run with the first version of spawnedprocess_extended.diff - built with my local.properties modified from how I normally build - got past both tests that have shown problems before and is still happily chugging along.\r\nSo that's very promising - Thank You Kristian!\r\nI'll interrupt that run now, pick up the latest patch, revert my build environment, and kick off a new run with the second version of that patch.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-14T00:28:09.562+0000","updated":"2012-02-14T00:28:09.562+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207433","id":"13207433","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"The second version of spawnedprocess_extended.diff built without trouble in my original build environment, and has also past the NetworkServerControlApiTest.test_01_WrongUsage, and the SecureServerTest without hitting any failures.\r\nThe test run is still going, but it's looking good so far.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-14T01:25:29.077+0000","updated":"2012-02-14T01:25:29.077+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207819","id":"13207819","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"The good news is, the last run did not show any problems with SpawnedProcess. \r\nI think the latest patch to SpawnedProcess etc. is good to commit. \r\n\r\nUnfortunately, the run still keeled over in testBoundaries, as before, and had many failures after that, also as before, (apparently) because of Derby System Shutdown messages. \r\nI'll see if I can analyze this failure further. \r\n\r\n1) testBoundaries(org.apache.derbyTesting.functionTests.tests.jdbcapi.InternationalConnectTest)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XJ001, SQLERRMC: java.security.AccessControlException\u0014Access denied (java.io.FilePermission [editedpath]\\system\\AAAA[...editedfilenameforformatting...]AAA\\tmp delete)\u0014XJ001.U\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:99)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:364)\r\n\tat org.apache.derby.jdbc.ClientDriver.connect(ClientDriver.java:166)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:317)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:273)\r\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.InternationalConnectTest.testBoundaries(InternationalConnectTest.java:120)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:51)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:18)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:51)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XJ001, SQLERRMC: java.security.AccessControlException\u0014Access denied (java.io.FilePermission [editedpath]\\system\\AAA[...editedfilenameforformatting...]AAA\\tmp delete)\u0014XJ001.U\r\n\tat org.apache.derby.client.am.Connection.completeSqlca(Connection.java:2125)\r\n\tat org.apache.derby.client.net.NetConnectionReply.parseRdbAccessFailed(NetConnectionReply.java:538)\r\n\tat org.apache.derby.client.net.NetConnectionReply.parseAccessRdbError(NetConnectionReply.java:431)\r\n\tat org.apache.derby.client.net.NetConnectionReply.parseACCRDBreply(NetConnectionReply.java:294)\r\n\tat org.apache.derby.client.net.NetConnectionReply.readAccessDatabase(NetConnectionReply.java:121)\r\n\tat org.apache.derby.client.net.NetConnection.readSecurityCheckAndAccessRdb(NetConnection.java:826)\r\n\tat org.apache.derby.client.net.NetConnection.flowSecurityCheckAndAccessRdb(NetConnection.java:762)\r\n\tat org.apache.derby.client.net.NetConnection.flowUSRIDONLconnect(NetConnection.java:603)\r\n\tat org.apache.derby.client.net.NetConnection.flowConnect(NetConnection.java:410)\r\n\tat org.apache.derby.client.net.NetConnection.<init>(NetConnection.java:220)\r\n\tat org.apache.derby.client.net.NetConnection40.<init>(NetConnection40.java:74)\r\n\tat org.apache.derby.client.net.ClientJDBCObjectFactoryImpl40.newNetConnection(ClientJDBCObjectFactoryImpl40.java:269)\r\n\tat org.apache.derby.jdbc.ClientDriver.connect(ClientDriver.java:100)\r\n\t... 41 more","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-14T16:43:32.316+0000","updated":"2012-02-14T16:43:32.316+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207823","id":"13207823","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"The latest failures actually look like DERBY-4836. I'll check on my jvm version.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-14T16:50:26.537+0000","updated":"2012-02-14T16:50:26.537+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13207855","id":"13207855","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Sure enough, I was picking up the wrong version because of the different PATH setting syntax for cygwin. Hence the cascading errors after InternationalConnectTest.\r\n\r\nStill, there was a hang in NativeAuthenticationServiceTest which Rick fixed, and I think the SpawnedProcess improvements are also valuable...So +1 to commit those changes.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-14T17:40:13.529+0000","updated":"2012-02-14T17:40:13.529+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13208369","id":"13208369","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Thanks for testing the SpawnedProcess patch, Myrna.\r\nI've created DERBY-5617 to track that work.\r\n\r\nIf you still have the logs (stdout and stderr), do you mind grepping for '{SpawnedProcess}' and post whatever you find?\r\nAlso, did the test run take a lot longer than without the patch?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-15T11:11:23.366+0000","updated":"2012-02-15T11:11:23.366+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13209748","id":"13209748","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I removed the runs before I saw this message.\r\nI did, however, check for SpawnedProcess and it did not show up anymore with the latest patch.\r\n\r\nI can run a suites.All run of the builds with and without your patch if you like to know the time difference, but that will take a while. I'll post that info in DERBY-5617.\r\n\r\nIn the mean time, I think *this* issue can be closed - perhaps 'invalid' is the best, or perhaps 'duplicate' as the cascading errors were a combination of my mistake and a jvm bug, the NativeAuthenticationTest and Interrupt errors are (being) addressed in different issues.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-16T21:20:36.090+0000","updated":"2012-02-16T21:20:36.090+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13209864","id":"13209864","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I am marking this as a duplicate of DERBY-4836, because of the cascading errors after InternationalConnectTest.testBoundaries failure.\r\nNativeAuthenticationTest issue has been fixed in DERBY-5608.\r\nUsing a later JVM version, I do not see an InterruptException, so that too is likely a jvm bug, or at least jvm-related.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-02-16T23:05:21.775+0000","updated":"2012-02-16T23:05:21.775+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13210111","id":"13210111","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"It's not that important for me. If you have deleted the output, don't rerun the tests.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-02-17T07:11:06.765+0000","updated":"2012-02-17T07:11:06.765+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12541126/comment/13685336","id":"13685336","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"[bulk update] Close all resolved issues that haven't been updated for more than one year.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2013-06-17T09:19:43.322+0000","updated":"2013-06-17T09:19:43.322+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5601/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06j4f:"}}