{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12549919","self":"https://issues.apache.org/jira/rest/api/latest/issue/12549919","key":"DERBY-5686","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[],"aggregatetimespent":null,"resolution":null,"customfield_12310220":"2012-04-27 05:46:48.921","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"234910","customfield_12310222":null,"customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":null,"workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5686/watchers","watchCount":3,"isWatching":false},"created":"2012-04-06T18:57:30.624+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":["derby_triage10_10"],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"8.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12326659","id":"12326659","description":"candidate for Second release for 10.10 branch","name":"10.10.2.0","archived":false,"released":true,"releaseDate":"2014-04-15"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12356754","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12356754","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12547686","key":"DERBY-5669","self":"https://issues.apache.org/jira/rest/api/2/issue/12547686","fields":{"summary":"(net)jdbcapi.DboPowersTest.testHardUpgrade test cleanup fails to delete files/directory - this leads to cascade of 225 errors in test run","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/2","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/critical.png","name":"Critical","id":"2"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12356753","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12356753","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12538857","key":"DERBY-5572","self":"https://issues.apache.org/jira/rest/api/2/issue/12538857","fields":{"summary":"multiple errors in nightly tests during DriverMgrAuthenticationTest test. reason: Connection authentication failure occurred.  Reason: userid or password invalid.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12356755","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12356755","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12540202","key":"DERBY-5588","self":"https://issues.apache.org/jira/rest/api/2/issue/12540202","fields":{"summary":"intermittent number of failures in the nightly regression suite  with nested error: ERROR 25502: An SQL data change is not permitted for a read-only connection, user or database.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12356752","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12356752","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12548219","key":"DERBY-5672","self":"https://issues.apache.org/jira/rest/api/2/issue/12548219","fields":{"summary":"Multiple failures in jdbcapi.XADSAuthenticationTest starting with  testUserFunctions(org.apache.derbyTesting.functionTests.tests.jdbcapi.XADSAuthenticajava.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12356756","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12356756","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12553388","key":"DERBY-5735","self":"https://issues.apache.org/jira/rest/api/2/issue/12553388","fields":{"summary":"2 failures in Derby2017LayerATest on trunk(revision 1332036) with ibm17","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12358201","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12358201","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12547284","key":"DERBY-5665","self":"https://issues.apache.org/jira/rest/api/2/issue/12547284","fields":{"summary":"nightly regression test failure in rollForwardBackup: ERROR XSRS4: Error renaming file (during backup) from extinout\\mybackup\\wombat to extinout\\mybackup\\wombat.OLD.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12358200","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12358200","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12547292","key":"DERBY-5666","self":"https://issues.apache.org/jira/rest/api/2/issue/12547292","fields":{"summary":"nightly suite error in NativeAuthenticationServiceTest : Database restoration unexpectedly failed.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12352347","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12352347","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12556076","key":"DERBY-5766","self":"https://issues.apache.org/jira/rest/api/2/issue/12556076","fields":{"summary":"BaseDataFileFactory.boot() should log the exception that causes it to boot the database read only ","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/1","description":"The issue is open and ready for the assignee to start work on it.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/open.png","name":"Open","id":"1","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"New"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12356757","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12356757","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12314126","key":"DERBY-555","self":"https://issues.apache.org/jira/rest/api/2/issue/12314126","fields":{"summary":"Unable to restart after disk is full","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/2","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/critical.png","name":"Critical","id":"2"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12350281","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12350281","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12538857","key":"DERBY-5572","self":"https://issues.apache.org/jira/rest/api/2/issue/12538857","fields":{"summary":"multiple errors in nightly tests during DriverMgrAuthenticationTest test. reason: Connection authentication failure occurred.  Reason: userid or password invalid.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12351294","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12351294","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12540202","key":"DERBY-5588","self":"https://issues.apache.org/jira/rest/api/2/issue/12540202","fields":{"summary":"intermittent number of failures in the nightly regression suite  with nested error: ERROR 25502: An SQL data change is not permitted for a read-only connection, user or database.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12351295","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12351295","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12548219","key":"DERBY-5672","self":"https://issues.apache.org/jira/rest/api/2/issue/12548219","fields":{"summary":"Multiple failures in jdbcapi.XADSAuthenticationTest starting with  testUserFunctions(org.apache.derbyTesting.functionTests.tests.jdbcapi.XADSAuthenticajava.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12351359","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12351359","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12553388","key":"DERBY-5735","self":"https://issues.apache.org/jira/rest/api/2/issue/12553388","fields":{"summary":"2 failures in Derby2017LayerATest on trunk(revision 1332036) with ibm17","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}}],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2014-04-16T02:41:05.123+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/1","description":"The issue is open and ready for the assignee to start work on it.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/open.png","name":"Open","id":"1","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"New"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11413","id":"11413","name":"Test"}],"timeoriginalestimate":null,"description":"8 errors in nightly test runs on 4/4/2012 against trunk, windows, ibm16, build 1310147 .  Tests passed against same build, same machine on ibm15 and ibm17\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1310147-suites.All_diff.txt\r\nThere were 8 errors:\r\n1) testNotFullAccessUsers(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setProperties(DatabasePropertyTestSetup.java:352)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setUp(DatabasePropertyTestSetup.java:268)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 47 more\r\n2) testNotFullAccessUsers(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:294)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 41 more\r\n3) testChangePasswordAndDatabasePropertiesOnly(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setProperties(DatabasePropertyTestSetup.java:352)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setUp(DatabasePropertyTestSetup.java:268)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 47 more\r\n4) testChangePasswordAndDatabasePropertiesOnly(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:294)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 41 more\r\n5) testGreekCharacters(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setProperties(DatabasePropertyTestSetup.java:352)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setUp(DatabasePropertyTestSetup.java:268)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 47 more\r\n6) testGreekCharacters(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:294)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 41 more\r\n7) testSystemShutdown(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setProperties(DatabasePropertyTestSetup.java:352)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setUp(DatabasePropertyTestSetup.java:268)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 47 more\r\n8) testSystemShutdown(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:294)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 41 more\r\n\r\nFAILURES!!!\r\nTests run: 15467,  Failures: 0,  Errors: 8\r\n\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10369","value":"Regression Test Failure","id":"10369"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"35344","summary":"multiple intermittent errors in nightly tests during DriverMgrAuthenticationTest test. reason: An SQL data change is not permitted for a read-only connection, user or database. \t","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"Most often seen with trunk, on: Windows XP (Professional Version 2002, SP3) Intel(R) Xeon(TM) CPU 2.40 GHz 2.39 GHz, 3.87 GB of RAM. Hyperthreading on or off. JVM version seems not to matter (seen with ibm 1.5, 1.6, 1.7, weme6.2). Machine runs 4 jvm suites.All runs concurrently, so heavily loaded. Similar load on a windows XP on VMWare similuated with Xeon(TM) MP CPU 3.33GHz, 3.34GHz machine does not display this behavior.\r\nOnce a variation was seen (see DERBY-5735) on another machine (Windows 2008, 4 CPU) with 10.8.\r\n","customfield_12311020":null,"customfield_12310050":{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10052","value":"Normal","id":"10052"},"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":31,"total":31,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13248651","id":"13248651","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"I spent some time looking at code and the 4/4/2012 error.  I think we are seeing this error intermittently across builds and across jvms.  I had\r\nbeen interpreting the read only message as something to do with left over files and maybe somehow booting on files being left over and still open\r\non windows and then derby falling over to readonly.  I see that the DriverMgrAuthenticationTest does as bunch of playing with readonly authentication,\r\nand now am wondering if the setup and/or tearDown routines are somehow getting a left over readonly connection and fail since they need \r\nwrite access.\r\n\r\nSo for this case we have 8 errors and no failures, but each of the errors causes a whole test to just not run so more serious.  \r\nFrom this test run we have the following from test run:\r\n(net)jdbcapi.AutoGenJDBC30Test.testUserGivenColumnsNull used 110 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testConnectShutdownAuthentication used 12453 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testUserFunctions used 1312 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testNotFullAccessUsers used 2594 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testChangePasswordAndDatabasePropertiesOnly used 1531 ms .\r\n\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testGreekCharacters used 6453 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testSystemShutdown used 6968 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testConnectShutdownAuthentication used 7921 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testUserFunctions used 2422 ms EEEEEEEE<assertDirectoryDeleted> attempt 1 left 2 files/dirs behind: 0=D:\\jartest\\JarResults.2012-04-05\\ibm16_suites.All\\system\\singleUse\\oneusec0\\db.lck 1=D:\\jartest\\JarResults.2012-04-05\\ibm16_suites.All\\system\\singleUse\\oneusec0\r\n.\r\n(emb)jdbcapi.PoolDSAuthenticationTest.testConnectShutdownAuthentication used 19859 ms .\r\n\r\nIt looks to me like network version of testUserFunctions ran and then we started having problems setting up to run\r\nnetwork testNotFullAccessUsers, and all the rest of the tests left in the suite. \r\n\r\nThe end of the testUserFunctions has the following code:\r\n  // reset\r\n  conn1 = openDefaultConnection(\"dan\", (\"dan\" + PASSWORD_SUFFIX));\r\n  setDatabaseProperty(\r\n      \"derby.database.defaultConnectionMode\",\"fullAccess\", conn1);\r\n  setDatabaseProperty(\r\n      \"derby.connection.requireAuthentication\",\"false\", conn1);\r\n  stmt = conn1.createStatement();\r\n  assertUpdateCount(stmt, 0, \"drop table APP.t1\");\r\n  conn1.commit();\r\n  stmt.close();\r\n  conn1.close();\r\n\r\nI am tempted to add a shutdown database here, and reopen default connection to just make sure the next test's setup has the right\r\nconnection.  Or could add some retry logic in the setup and teardown - not sure how easy that would be.  But I don't want to mask a real code bug.  I am wondering if there is any sort of connection caching that we are doing that\r\nmight not be correctly clearing readonly access?  I seem to remember past bugs where a reused connection would have some left over attribute\r\nsometimes that was not meant to be.  \r\n\r\nI read the documentation and it doesn't explicitly say so, but it doesn't say not - so I assume that setting these database properties are\r\nsupposed to take effect immediately.  So my assumptions on derby correct behavior would be, but would appreciate opinions of those\r\nwith authentication expertise:\r\n\r\n1) existing connections don't change their access authentication\r\n2) new connections initiated after the commit of the database properties should pick up new default authentication.\r\n\r\nThe DatabasePropertyTestSetup.setUp code is going to use a connection that was produced from a getConnection() call which will use\r\nexisting test connection if it exists.\r\n\r\nOf course this would be all easier to understand if I could reproduce, but I have not been able to in my environment so this is all from \r\nlooking at static test results and the code.  Any opinions on next steps are appreciated. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-04-06T19:46:39.984+0000","updated":"2012-04-06T19:46:39.984+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13248653","id":"13248653","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"This issue may or may not be related to DERBY-5572 DERBY-5572 is getting userid-password errors instead of readonly.  But if problem is that a connection is being used that has leftover attributes from the test, then they could be same issue.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-04-06T19:49:08.300+0000","updated":"2012-04-06T19:49:08.300+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13248659","id":"13248659","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"I think this is the same issue, though shows different tests failing and only 4 errors.  failed windows, ibm16, build 1308644, 4/2/2012\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1308644-suites.All_diff.txt\r\n\r\n1) testSystemShutdown(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedCallableStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedPreparedStatement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest.setDatabaseProperty(AuthenticationTest.java:1297)\r\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest.setUp(AuthenticationTest.java:192)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)\r\n\t... 63 more\r\nCaused by: ERROR 25502: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.impl.sql.conn.GenericAuthorizer.authorize(Unknown Source)\r\n\tat org.apache.derby.exe.ac0249415ax0136x76efxea75xffff977260360.g0(Unknown Source)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\r\n\t... 57 more\r\n2) testSystemShutdown(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedCallableStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:294)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat <unknown class>.<unknown method>(Unknown Source)\r\n\t... 55 more\r\nCaused by: ERROR 25502: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.impl.sql.conn.GenericAuthorizer.authorize(Unknown Source)\r\n\tat org.apache.derby.exe.acfb4d815dx0136x76efxea75xffff977260360.g0(Unknown Source)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\r\n\t... 49 more\r\n3) testSystemShutdown(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)\r\n\tat org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)\r\n\tat org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)\r\n\tat org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:379)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:354)\r\n\tat org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:100)\r\n\tat org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:67)\r\n\tat org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:43)\r\n\tat org.apache.derbyTesting.junit.TestConfiguration.openDefaultConnection(TestConfiguration.java:1633)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestSetup.getConnection(BaseJDBCTestSetup.java:72)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:280)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)\r\n\t... 53 more\r\n4) testSystemShutdown(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverMgrAuthenticationTest)java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)\r\n\tat org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)\r\n\tat org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)\r\n\tat org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:379)\r\n\tat java.sql.DriverManager.getConnection(DriverManager.java:354)\r\n\tat org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:100)\r\n\tat org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:67)\r\n\tat org.apache.derbyTesting.junit.DriverManagerConnector.openConnection(DriverManagerConnector.java:43)\r\n\tat org.apache.derbyTesting.junit.TestConfiguration.openDefaultConnection(TestConfiguration.java:1633)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestSetup.getConnection(BaseJDBCTestSetup.java:72)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:280)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: java.sql.SQLException: Connection authentication failure occurred.  Reason: Invalid authentication..\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)\r\n\t... 48 more\r\nThere was 1 failure:\r\n1) DriverMgrAuthenticationTestjunit.framework.AssertionFailedError: Failed to delete 14 files (root=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf): D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c10.dat (isDir=false, canRead=true, canWrite=true, size=20480), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c180.dat (isDir=false, canRead=true, canWrite=true, size=36864), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c191.dat (isDir=false, canRead=true, canWrite=true, size=16384), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c20.dat (isDir=false, canRead=true, canWrite=true, size=32768), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c51.dat (isDir=false, canRead=true, canWrite=true, size=16384), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c60.dat (isDir=false, canRead=true, canWrite=true, size=12288), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c71.dat (isDir=false, canRead=true, canWrite=true, size=8192), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c90.dat (isDir=false, canRead=true, canWrite=true, size=24576), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ca1.dat (isDir=false, canRead=true, canWrite=true, size=24576), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cc0.dat (isDir=false, canRead=true, canWrite=true, size=8192), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cd1.dat (isDir=false, canRead=true, canWrite=true, size=8192), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ce1.dat (isDir=false, canRead=true, canWrite=true, size=8192), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0 (isDir=true, canRead=true, canWrite=true, size=0), D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf (isDir=true, canRead=true, canWrite=true, size=0)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertDirectoryDeleted(BaseJDBCTestCase.java:1491)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup.removeDir(DropDatabaseSetup.java:120)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup.access$000(DropDatabaseSetup.java:35)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup$1.run(DropDatabaseSetup.java:106)\r\n\tat java.security.AccessController.doPrivileged(AccessController.java:202)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup.removeDirectory(DropDatabaseSetup.java:103)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup.removeDirectory(DropDatabaseSetup.java:99)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup.removeDatabase(DropDatabaseSetup.java:92)\r\n\tat org.apache.derbyTesting.junit.DropDatabaseSetup.tearDown(DropDatabaseSetup.java:78)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\r\nFAILURES!!!\r\nTests run: 15471,  Failures: 1,  Errors: 4\r\n\r\n\r\nHere is the output from when the test failed:\r\n(net)jdbcapi.AutoGenJDBC30Test.testUserGivenColumnsNull used 94 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testConnectShutdownAuthentication used 27905 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testUserFunctions used 2469 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testNotFullAccessUsers used 765 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testChangePasswordAndDatabasePropertiesOnly used 1000 ms .\r\n\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testGreekCharacters used 7656 ms .\r\n(emb)jdbcapi.DriverMgrAuthenticationTest.testSystemShutdown java.io.FileNotFoundException: system\\singleUse\\oneusebf\\db.lck (Access is denied.)\r\n\tat java.io.FileInputStream.open(Native Method)\r\n\tat java.io.FileInputStream.<init>(FileInputStream.java:137)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.copySingleFile(PrivilegedFileOpsForTests.java:304)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.recursiveCopy(PrivilegedFileOpsForTests.java:276)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.access$000(PrivilegedFileOpsForTests.java:49)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests$8.run(PrivilegedFileOpsForTests.java:235)\r\n\tat java.security.AccessController.doPrivileged(AccessController.java:251)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.copy(PrivilegedFileOpsForTests.java:233)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:137)\r\n\tat junit.framework.TestResult$1.protect(TestResult.java:106)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.framework.TestResult.run(TestResult.java:109)\r\n\tat junit.framework.TestCase.run(TestCase.java:120)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n\tat junit.textui.TestRunner.start(TestRunner.java:185)\r\n\tat junit.textui.TestRunner.main(TestRunner.java:143)\r\nused 1484 ms EEEE<assertDirectoryDeleted> attempt 1 left 15 files/dirs behind: 0=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\db.lck 1=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c10.dat 2=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c180.dat 3=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c191.dat 4=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c20.dat 5=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c51.dat 6=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c60.dat 7=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c71.dat 8=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c90.dat 9=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ca1.dat 10=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cc0.dat 11=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cd1.dat 12=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ce1.dat 13=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0 14=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\r\n<assertDirectoryDeleted> attempt 2 left 14 files/dirs behind: 0=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c10.dat 1=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c180.dat 2=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c191.dat 3=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c20.dat 4=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c51.dat 5=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c60.dat 6=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c71.dat 7=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c90.dat 8=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ca1.dat 9=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cc0.dat 10=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cd1.dat 11=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ce1.dat 12=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0 13=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\r\n<assertDirectoryDeleted> attempt 3 left 14 files/dirs behind: 0=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c10.dat 1=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c180.dat 2=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c191.dat 3=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c20.dat 4=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c51.dat 5=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c60.dat 6=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c71.dat 7=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c90.dat 8=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ca1.dat 9=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cc0.dat 10=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cd1.dat 11=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ce1.dat 12=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0 13=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\r\n<assertDirectoryDeleted> attempt 4 left 14 files/dirs behind: 0=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c10.dat 1=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c180.dat 2=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c191.dat 3=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c20.dat 4=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c51.dat 5=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c60.dat 6=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c71.dat 7=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\c90.dat 8=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ca1.dat 9=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cc0.dat 10=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\cd1.dat 11=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0\\ce1.dat 12=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\\seg0 13=D:\\jartest\\JarResults.2012-04-02\\ibm16_suites.All\\system\\singleUse\\oneusebf\r\nF.\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testConnectShutdownAuthentication used 4625 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testUserFunctions used 937 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testNotFullAccessUsers used 1188 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testChangePasswordAndDatabasePropertiesOnly used 578 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testGreekCharacters used 2219 ms .\r\n(net)jdbcapi.DriverMgrAuthenticationTest.testSystemShutdown used 1188 ms .\r\n(emb)jdbcapi.PoolDSAuthenticationTest.testConnectShutdownAuthentication used 6391 ms .\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-04-06T19:54:56.598+0000","updated":"2012-04-06T19:54:56.598+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13263367","id":"13263367","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Attaching a patch which modifies DatabasePropertyTestSetup to catch SQLSTATE 25502 in the teardown method; and gather some info and print it out, and then close the current connection, and retry the same clearing of properties with a new connection.\r\n\r\nHopefully this will clear the problem, if not, at least it will give us a bit more insight in the state of the connection when we see this.\r\n\r\nPatch ready for review.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-04-27T05:46:48.921+0000","updated":"2012-04-27T05:46:48.921+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13263997","id":"13263997","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I committed my patch. \r\nIf the error is not seen, it won't affect the run, and if it *is* seen in the teardown method of the DatabasePropertyTestSetup, we'll hopefully see some info. \r\n\r\nHowever, I don't think this will solve the issue - or at least not entirely, because it doesn't seem to be always the DatabasePropertyTestSetup that's involved, nor is it always 'SQL'. For instance, it can also be 'DDL' i.e. ERROR 25503 (instead of 25502), see the stacktrace of the first failure with weme 6.2 on 4/25 (http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/weme6.2/1330624-suites.All_diff.txt);\r\n 1)\r\n testDropTableAfterUpgradeWithConstraint(org.apache.derbyTesting.functionTests.tests.upgradeTests.BasicSetup)java.sql.SQLException: DDL is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.upgradeTests.BasicSetup.testDropTableAfterUpgradeWithConstraint(BasicSetup.java:286)\r\n\tat java.lang.reflect.AccessibleObject.invokeV(AccessibleObject.java:195)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: ERROR 25503: DDL is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.impl.sql.conn.GenericAuthorizer.authorize(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.GenericResultSetFactory.getDDLResultSet(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.ConstantActionActivation.execute(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericActivationHolder.execute(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\r\n\t... 101 more\r\n------------------------\r\n\r\nThis however seems related to a java.io.FileNotFoundException on db.lck which is printed earlier in the output, but apparently not causing a failure:\r\n\r\n------------------------\r\n(emb)upgradeTests.BasicSetup.testDropTableAfterUpgradeWithConstraint java.io.FileNotFoundException: system\\singleUse\\oneusecb\\db.lck (A component of the path name does not exist)\r\n\tat java.io.FileInputStream.<init>(FileInputStream.java:55)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.copySingleFile(PrivilegedFileOpsForTests.java:304)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.recursiveCopy(PrivilegedFileOpsForTests.java:276)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.access$000(PrivilegedFileOpsForTests.java:49)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests$8.run(PrivilegedFileOpsForTests.java:235)\r\n\tat java.security.AccessController.doPrivileged(AccessController.java:255)\r\n\tat org.apache.derbyTesting.functionTests.util.PrivilegedFileOpsForTests.copy(PrivilegedFileOpsForTests.java:233)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:137)\r\n\tat junit.framework.TestResult$1.protect(TestResult.java:106)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.framework.TestResult.run(TestResult.java:109)\r\n\tat junit.framework.TestCase.run(TestCase.java:120)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.framework.TestResult.runProtected(TestResult.java:124)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n\tat junit.framework.TestSuite.run(TestSuite.java:225)\r\n\tat junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n\tat junit.textui.TestRunner.start(TestRunner.java:185)\r\n\tat junit.textui.TestRunner.main(TestRunner.java:143) \r\n------------------------\r\n\r\nBut we'll wait and see what happens.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-04-27T21:38:17.472+0000","updated":"2012-04-27T21:38:17.472+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13265215","id":"13265215","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"We did not hit the error during DatabasePropertyTestSetup.teardown, so I don't know whether we now would get more useful output, but we did hit another occurrence - this time during DatabasePropertyTestSetup.setUp()- see: \r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm17/1332036-suites.All_diff.txt\r\n\r\nThe stack of the first failure:\r\n---------------------------  \r\n1) testEmbeddedAttributes(org.apache.derbyTesting.functionTests.tests.jdbcapi.DriverTest)java.sql.SQLException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setProperties(DatabasePropertyTestSetup.java:392)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setUp(DatabasePropertyTestSetup.java:272)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: An SQL data change is not permitted for a read-only connection, user or database.\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readExecuteCall_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readExecuteCall(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\r\n\t... 29 more\r\n\r\nAs happens sometimes, there was no actual 'fail' directory for this; the only fail dirs created were for the subsequent jdbcapi.Derby2017LayerATest failures which report the DDL read-only message (SQLState Error 25503). I think those failures are likely later - the first occurrence is the .SQLState Error 25502.\r\n\r\nI am attaching a patch - DERBY-5686_2.diff which tries to catch this error during setUp by adding similar code as was added for the teardown() to the setProperties method.\r\n\r\nReview is welcome, otherwise I'll commit this in a couple of hours.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-04-30T21:06:53.441+0000","updated":"2012-04-30T21:06:53.441+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13265552","id":"13265552","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I committed the _2.diff patch with revision 1332484.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-01T00:45:56.411+0000","updated":"2012-05-01T00:45:56.411+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13267664","id":"13267664","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Unfortunately, my changes weren't enough to make the test pass - see:\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm15/1332892-suites.All_diff.txt\r\nand\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm16/1332892-suites.All_diff.txt\r\nThe ibm 1.5 failure was in DatabasePropertyTestSetup.teardown(), but the new connection was also reported as readOnly, so retry was pointless. I'm not any further in understanding where it (the connection or the database?) was set to readOnly.\r\nOne theory was that an earlier test did a setReadOnly and that this somehow propogated - jdbcapi.DataSourceTest and jdbcapi.J2EEDataSourceTest do this at some point - but in the ibm 1.5 failures, as in several earlier cases, those 2 tests either didn't run at all (e.g. with 1.7 jvm) or didn't run before the first failure.\r\nAfter the initial failure we see a host of other trouble such as invalid authentication errors.\r\n\r\nThe ibm 1.6 failure shows that it did hit the additional code in DatabasePropertyTestSetup.setProperties, but unfortunately the code I added to do conn.close() failed, because the transaction is still open (causing different failures than before, not helping matters).\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-03T18:28:19.232+0000","updated":"2012-05-03T18:28:19.232+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13267720","id":"13267720","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Attaching patch DERBY-5686_3, which modifies the logic in assertDirectoryDeleted to tolerate that the root directory for some reason gets unexpectedly deleted.\r\nNote that the method will still fail if the directory doesn't exist in the first iteration.\r\n\r\nPatch ready for review. \r\n\r\nFYI, I saw that one test failed because of the old logic in the ibm16 run Myrna referred to. The only file that couldn't be deleted was db.lck. The root directory wasn't listed as \"undeletable\". Probably db.lck was attempted deleted early on while Derby was still running, and assertDirectoryDeleted deleted all the other files. I'm guessing that Derby deleted the lock file as part of shutdown before assertDirectoryDeleted got around to delete the root directory. Removing the directory succeeded because it would have been empty at that point.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-05-03T19:21:54.963+0000","updated":"2012-05-03T19:21:54.963+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13267967","id":"13267967","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I'm attaching another patch which tries to finagle the retrying/catch info code. This is still debugging code, and may possibly be removed/adjusted again later. Ready for review.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-04T00:05:46.089+0000","updated":"2012-05-04T00:05:46.089+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13267971","id":"13267971","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Thanks for looking at this issue Kristian.\r\n+1 to implementing patch DERBY-5686_3.diff, it looks like a good improvement, although I think the error related to assertDirectoryDeleted is a result of the earlier failures, or at least a later issue...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-04T00:08:06.064+0000","updated":"2012-05-04T00:08:06.064+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13268897","id":"13268897","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Committed patch 3 to trunk with revision 1334313.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-05-05T04:23:16.383+0000","updated":"2012-05-05T04:23:16.383+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13270918","id":"13270918","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Unfortunately, the latest commit now causes a loop that we never break out of... \r\nThis for instance is the end of console output from a recent unfinished (and hence not published) test run before I killed the process:\r\n-------------------------------- \r\n(net)jdbcapi.InternationalConnectTest.testDriverManagerConnect used 13797 ms .\r\n(net)jdbcapi.InternationalConnectTest.testXADSConnect <assertDirectoryDeleted> attempt 1 left 1 files/dirs behind: 0=D:\\jartest\\JarResults.2012-05-07\\ibm17_suites.All\\system\\?\\tmp\r\n<assertDirectoryDeleted> root directory unexpectedly gone - delayed, external or concurrent delete?\r\n<assertDirectoryDeleted> attempt 1 left 1 files/dirs behind: 0=D:\\jartest\\JarResults.2012-05-07\\ibm17_suites.All\\system\\?\\tmp\r\n<assertDirectoryDeleted> root directory unexpectedly gone - delayed, external or concurrent delete?\r\n<assertDirectoryDeleted> attempt 1 left 1 files/dirs behind: 0=D:\\jartest\\JarResults.2012-05-07\\ibm17_suites.All\\system\\?\\tmp\r\n<assertDirectoryDeleted> root directory unexpectedly gone - delayed, external or concurrent delete?\r\n[....etc...] \r\n-------------------------------- \r\nDid we perhaps miss adding attempts++? I'm going to assume we did. I'll add a finally block... ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-08T23:12:48.057+0000","updated":"2012-05-08T23:12:48.057+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13270921","id":"13270921","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"committed adding a finally block with revision 1335820.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-08T23:19:29.609+0000","updated":"2012-05-08T23:19:29.609+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271268","id":"13271268","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Thanks, Myrna.\r\n\r\nSorry about that mistake. When I look at the code now, I believe I forgot a return-statement in the else-block (inside the catch-block).\r\nSee patch 3a, which also backs out the addition of the finally-block. While the unconditional increment of attempts breaks the loop, it will cause the test/setup to fail because fl will always contain at least one element. I suppose Java lists '?' as the directory name because it has been deleted.\r\n\r\nPatch ready for review.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-05-09T10:09:42.615+0000","updated":"2012-05-09T10:09:42.615+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271415","id":"13271415","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Thanks for the explanation Kristian. +1 for committing your update.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-09T13:46:55.127+0000","updated":"2012-05-09T13:46:55.127+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271588","id":"13271588","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"looks like the following is caused by retry logic not committing/aborting transaction before closing connection:\r\nhttp://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/ibm15/1335323-suites.All_diff.txt\r\n\r\nThere were 2 errors:\r\n1) testInvalidAlgorithmName(org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest)java.sql.SQLException: Cannot close a connection while a transaction is still active.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Connection.closeResourcesX(Unknown Source)\r\n\tat org.apache.derby.client.am.Connection.closeX(Unknown Source)\r\n\tat org.apache.derby.client.net.NetConnection.closeX(Unknown Source)\r\n\tat org.apache.derby.client.am.Connection.close(Unknown Source)\r\n\tat org.apache.derby.client.net.NetConnection.close(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setProperties(DatabasePropertyTestSetup.java:372)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.setUp(DatabasePropertyTestSetup.java:272)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: Cannot close a connection while a transaction is still active.\r\n\tat org.apache.derby.client.am.Connection.checkForTransactionInProgress(Unknown Source)\r\n\t... 51 more\r\n2) testInvalidAlgorithmName(org.apache.derbyTesting.functionTests.tests.jdbcapi.AuthenticationTest)java.sql.SQLException: Cannot close a connection while a transaction is still active.\r\n\tat org.apache.derby.client.am.SQLExceptionFactory.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Connection.closeResourcesX(Unknown Source)\r\n\tat org.apache.derby.client.am.Connection.closeX(Unknown Source)\r\n\tat org.apache.derby.client.net.NetConnection.closeX(Unknown Source)\r\n\tat org.apache.derby.client.am.Connection.close(Unknown Source)\r\n\tat org.apache.derby.client.net.NetConnection.close(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.DatabasePropertyTestSetup.tearDown(DatabasePropertyTestSetup.java:303)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: Cannot close a connection while a transaction is still active.\r\n\tat org.apache.derby.client.am.Connection.checkForTransactionInProgress(Unknown Source)\r\n\t... 45 more","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-05-09T16:57:29.629+0000","updated":"2012-05-09T16:57:29.629+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271621","id":"13271621","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Yes, that's why I put up my patch _4.diff on May 4...I was hoping for a review... \r\nBut now I'm working on an alternative that catches error 25001 (Cannot close a connection while a transaction is still active) and does a commit then tries the close again. I want to run a full test suite with this change, so it'll take a while.\r\nAlso I am working on some additional changes, because I think I've seen the error when it wasn't DatabasePropertyTestSetup that reported the db to be read-only.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-09T17:38:49.966+0000","updated":"2012-05-09T17:38:49.966+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271634","id":"13271634","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Committed patch 3a to trunk with revision 1336316.\r\nSorry for polluting your issue, Myrna. I'll take a look at your next patch and see if I can contribute with anything of value.\r\nDo you mind filling out the environment-field of this issue?\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-05-09T17:55:21.878+0000","updated":"2012-05-09T17:55:21.878+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271638","id":"13271638","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Attaching another patch, which tries to address the situation where the retry logic in DatabasePropertyTestSetup would get an error. This also adds some code to cleanDatabaseTestSetup to catch tests leaving the connection in read-only state.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-09T17:59:24.740+0000","updated":"2012-05-09T17:59:24.740+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13271697","id":"13271697","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Thanks Kristian. The review comment wasn't necessarily directed at you...Plus I forgot to set the patch available flag.\r\nI feel better about the _5.diff and committed it already - revision 1336349. \r\nI updated the environment field of this issue.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-09T18:51:16.610+0000","updated":"2012-05-09T18:51:16.610+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13272880","id":"13272880","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Attaching a patch which tries to address another possible cause for the problems - perhaps the shutdown reports it's finished before it's actually completely shutdown.\r\nSo this patch tries to check whether the db.lck and/or (for unix) dbex.lck file(s) are still present - if so, loop until they're gone, then continue to delete the database.\r\n\r\nThis patch passed on my system (a different one from where the test failures are seen). Patch ready for review.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-10T23:11:11.809+0000","updated":"2012-05-10T23:11:11.809+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13273054","id":"13273054","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"Thanks for updating the environment field, Myrna.\r\n\r\nIs patch 6 temporary, or is it intended as a permanent addition?\r\n\r\nEspecially if the latter, I have a few questions and comments:\r\n o Are there cases where the lock files won't be removed for some reason?\r\n    If yes, then there should be a timeout function, i.e. don't wait for more than X minutes.\r\n o You can avoid the boolean by using break, but with a timeout the loop will probably be rewritten anyway.\r\n o This patch masks an issue. I'd like it to print something if it has to wait, similar to what assertDirectoryDeleted does, as an incentive/reminder for fixing the real issue.\r\n    I expect that with patch 6 committed, you shouldn't see any more output from assertDirectoryDeleted, except for in cases where there's a real bug with not closing file handles.\r\n\r\nThe theory about the database shutdown now being complete is pretty much confirmed, since the file deletion logic has failed deleting db.lock and tmp. Both of these are supposed to be removed by Derby when it has shut down properly. I don't know if this is the reason for the read-only connections, but it will be good to rule that out.\r\n\r\nDo we know if the database goes read-only on boot, or if it turns read-only after being booted?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2012-05-11T05:23:30.310+0000","updated":"2012-05-11T05:23:30.310+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13276321","id":"13276321","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Patch 6 was intended as a more permanent solution - if it did solve the problem...\r\nBut we're still unclear on what causes derby to think the db is read-only.\r\n\r\nOne part of the trouble is that this machine was running our nightly tests - meaning I only had a small time frame to debug/analyze/run experiments. I now switched the nightly runs to another machine, so I can debug/experiment better. At which point I don't need to commit to see the bad results, so the patch doesn't need to go in until we're sure it's fixing the trouble.\r\n\r\nTo go into your questions (answers with a:)\r\no Are there cases where the lock files won't be removed for some reason?\r\n   If yes, then there should be a timeout function, i.e. don't wait for more than X minutes.  \r\na:   I think this is what we're concerned about. Shutdown() should remove the lock files, but in this case it seems sometimes they're not removed, there seems to be a timing issue. The theory there is that if db.lck is present, we'll get an 25502 error. \r\n   And you're right - there needs to be a timeout, possibly with some message.\r\no You can avoid the boolean by using break, but with a timeout the loop will probably be rewritten anyway. \r\na:  You're right.\r\no This patch masks an issue. I'd like it to print something if it has to wait, similar to what assertDirectoryDeleted does, as an incentive/reminder for fixing the real issue. \r\na: Printing something makes sense, I'll work on that.\r\n\r\nq:  Do we know if the database goes read-only on boot, or if it turns read-only after being booted? \r\na: we don't know...It would be good to figure this out too...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-15T23:09:50.342+0000","updated":"2012-05-15T23:09:50.342+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13277060","id":"13277060","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Although not well understood the connection between the tests and the , errors. At least the error that occurs in DERBY-5766 seems the same, so linking the issue","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-05-16T19:58:04.519+0000","updated":"2012-05-16T19:58:04.519+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13278337","id":"13278337","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Attaching another version of the patch which I think addresses Kristian's comments. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-05-17T22:17:51.006+0000","updated":"2012-05-17T22:17:51.006+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13286914","id":"13286914","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Hi Myrna, I think your patch from the 17th is safe to commit. I wonder where are the single use databases shutdown. It seems it is mostly those that relate to the failures in DERBY-5686","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-05-31T20:43:35.970+0000","updated":"2012-05-31T20:43:35.970+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13288951","id":"13288951","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"The machine (results no longer published) was displaying the read-only trouble again on Friday night's run.\r\nI committed the patch _7.diff with revision 1346174.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-06-04T22:08:29.481+0000","updated":"2012-06-04T22:08:29.481+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13436135","id":"13436135","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Despite the patch, we kept seeing various read-only errors.\r\nI finally had the disk swapped for a new one, and I deleted some space on the way - and now the problems are gone.\r\nI added back in the largeDataTest suite, to see what happens.\r\n\r\nOn the whole, there have been a number of test failures reported that I think relate to the same issue. I'll mark all of those duplicates of this.\r\n\r\nAlso, there have been some reports from users complaining about sudden read-only databases.\r\nIt's something that can happen when the disk is full - in DERBY-555 Suresh hypothesized that this would happen if the db.lck file could not get created.\r\nhttps://issues.apache.org/jira/browse/DERBY-555?focusedCommentId=12320936&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12320936\r\nBut this is on booting the database. Was that the case with our failing test cases? Perhaps so, as in the case of it hitting through junit.DatabasePropertyTestSetup.\r\n\r\nHere are some relevant user questions:\r\nhttp://old.nabble.com/Derby-database-started-suddenly-in-READ-ONLY-mode-td33271488.html \r\nhttp://old.nabble.com/Derby-on-Tomcat-server-keeps-setting-itself-to-read-only-td23152838.html\r\nperhaps also http://forums.overclockers.co.uk/showthread.php?p=13923396 - maybe a case of running out of memory when tomcat is up?\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-08-16T17:31:53.958+0000","updated":"2012-08-16T17:31:53.958+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13440390","id":"13440390","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"After adding the largeDataSuite again, the machine apparently got so maxed out in some way (memory? There ought to have been enough disk space...) that I couldn't log on to look at anything.\r\nAutomatic reporting did see one occurrence of https://issues.apache.org/jira/browse/DERBY-5735.\r\n\r\nThen when I decided to boot the machine in order to stop the largeDataSuite again, it killed the disk.\r\nSo, there is still a possibility that this occurs, but I don't want to spend more time on this now. It may even be 'by design' (based on the comments in DERBY-555), but it would at least be nice if derby could give a better message, because when you see 'read-only', the logical assumption is that there is something wrong with permissions or read-only settings somewhere.\r\nUnassigning myself.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2012-08-23T15:41:24.673+0000","updated":"2012-08-23T15:41:24.673+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12549919/comment/13464192","id":"13464192","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Taking off of High Value Fix per Myrna's comments depriortizing the issue. The better error reporting she recommends will still be on  the High Value Fix list in the form of DERBY-5686","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2012-09-26T21:38:13.399+0000","updated":"2012-09-26T21:38:13.399+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5686/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06evj:"}}