{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12344800","self":"https://issues.apache.org/jira/rest/api/latest/issue/12344800","key":"DERBY-1440","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312590","id":"12312590","description":"","name":"10.3.1.4","archived":false,"released":true,"releaseDate":"2007-08-10"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2007-03-02 22:00:37.956","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"22507","customfield_12310222":"3_*:*_1_*:*_365073248_*|*_1_*:*_1_*:*_28975344004_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2007-05-28T14:01:45.252+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1440/watchers","watchCount":0,"isWatching":false},"created":"2006-06-22T23:54:48.000+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"3.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/11187","id":"11187","description":"","name":"10.2.1.6","archived":false,"released":true,"releaseDate":"2006-10-02"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12315257","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12315257","type":{"id":"12310010","name":"Incorporates","inward":"is part of","outward":"incorporates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310010"},"inwardIssue":{"id":"32841","key":"DERBY-310","self":"https://issues.apache.org/jira/rest/api/2/issue/32841","fields":{"summary":"Document and/or change Derby client code to match behavior with Embedded driver where possible.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/4","id":"4","description":"An improvement or enhancement to an existing feature or task.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/improvement.png","name":"Improvement","subtask":false}}}}],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2011-01-21T17:49:04.443+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11407","id":"11407","name":"JDBC"},{"self":"https://issues.apache.org/jira/rest/api/2/component/11690","id":"11690","name":"Network Client"},{"self":"https://issues.apache.org/jira/rest/api/2/component/11414","id":"11414","name":"Tools"}],"timeoriginalestimate":null,"description":"When running some SQL queries through ij that fails it seems like some\ninformation about chained exceptions is not presented to the user when\nrunning with the client driver and jdk 1.6.\n\n\nOne example SQL that fails (taken from the ieptests.sql):\n=========================================================\n\nij> call SYSCS_UTIL.SYSCS_EXPORT_TABLE ('inventory', 'ORDERTABLE' ,\n'extinout/order.dat', null, null, null) ;\n\nWhen running this in ij the following error message is produced:\n\n\n\nJava 1.6 Embedded driver:\n=========================\n\nERROR 38000: The exception 'java.sql.SQLSyntaxErrorException: Schema\n'inventory' does not exist' was thrown while evaluating an expression.\nERROR 42Y07: Schema 'inventory' does not exist\n\n\nJava 1.5 Client driver:\n=======================\n\nERROR 38000: The exception 'SQL Exception: Schema 'inventory' does not\nexist' was thrown while evaluating an expression. SQLSTATE: 42Y07:\nSchema 'inventory' does not exist\n\n\nJava 1.6 Client driver:\n=======================\n\nERROR 38000: The exception 'java.sql.SQLSyntaxErrorException: Schema\n'inventory' does not exist' was thrown while evaluating an expression.\n\n\nThe bug (or difference) here is that the client driver when running\nwith jdk 1.6 does not print the chained exception and SQL state.\nIt would be nice to have the same information in the output as what is\nwritten by the embedded driver (or client driver running with jdk\n1.5).\n\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"37563","summary":"jdk 1.6 client driver omits SQLStates and chained exceptions in error messages","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=olav","name":"olav","emailAddress":"olav dot sandstaa at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Olav Sandstaa","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=olav","name":"olav","emailAddress":"olav dot sandstaa at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Olav Sandstaa","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"Sun JDK 1.6","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":7,"total":7,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12477468","id":"12477468","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"body":"Ran into this converting importExport.java to JUnit. I was rather surprised by the lack of information provided by the JDBC 4 client driver and the fact that the exception message text no longer contained the SQLState of even the top-level exception, not to mention the SQLStates of the nested exceptions.\r\n\r\nAlso, linking this to DERBY-310, the master client/embedded differences issue. \r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"created":"2007-03-02T22:00:37.956+0000","updated":"2007-03-02T22:00:37.956+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12477470","id":"12477470","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"body":"Readjusting the summary to reflect that this is a general problem and not specific to ij.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"created":"2007-03-02T22:07:50.716+0000","updated":"2007-03-02T22:07:50.716+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12498558","id":"12498558","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"While working on DERBY-2472 I found out what caused this difference between the JDBC 3.0 driver and the JDBC 4.0 driver. There are three problems. Firstly, StandardException.unexpectedUserException() doesn't recognize that an SQLException is generated Derby since it is not an EmbedSQLException. Secondly, TransactionResourceImpl.wrapInSQLException() invokes SQLException.setNextException() explicitly so that the required chaining/ferrying logic in the exception factory and in EmbedSQLException's constructor is not used. Thirdly, SQLException40.wrapArgsForTransportAcrossDRDA() puts a standard SQLException, not an EmbedSQLException, in the argument ferry's next-exception chain, which prevents the network server from seeing it as a Derby exception.\r\n\r\nThe attached patch fixes the problem by\r\n  1) using SQLExceptionFactory.getArgumentFerry() to find out whether the exception is a Derby exception in unexpectedUserException()\r\n  2) using factory methods instead of setNextException() to do the chaining in wrapInSQLException()\r\n  3) improving Util.javaException() so that it sets up a next-exception chain if the Java exception contains nested exceptions\r\n  4) changing wrapArgsForTransportAcrossDRDA() to create an argument ferry whose next exception is the argument ferry of the main exception's next exception\r\n\r\nThis patch also fixes all the JUnit tests that contain code looking like this:\r\n\r\n    assertStatementError(JDBC.vmSupportsJDBC4() ? \"38000\" : \"42X62\", cSt);\r\n\r\nNow, the check for JDBC level is not needed anymore for those tests.\r\n\r\nDerbyall and suites.All ran cleanly on Java 1.5 and Java 1.6.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2007-05-24T09:23:10.650+0000","updated":"2007-05-24T09:23:10.650+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12498812","id":"12498812","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Patch looks good and it solves my issue from DERBY-2496.\r\n+1 to commit.\r\n\r\nMy only comment is that I did not quite follow the changes in TransactionResourceImpl.wrapInSQLException so maybe some explanation would be good there.\r\nIt seems nextSQLException here represents something different from what is handled by setNextException.  Maybe it would be better if it was called something else. Also I do not quite understand the role of seeNextException and the recursive call to wrapInSQLException.\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2007-05-24T20:30:32.068+0000","updated":"2007-05-24T20:30:32.068+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12498857","id":"12498857","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"Thanks for the review, Øystein! I have committed 1440.diff to trunk with revision 541435 and will address your comments in a follow-up patch by adding more comments to wrapInSQLException(). I agree that nextSQLException should be renamed to something which matches how it's currently being used.\r\n\r\nThe purpose of seeNextException and the recursive call to wrapInSQLException() is to convert a StandardException to an SQLException and add a next pointer from the SQLException to another SQLException which wraps the cause of the StandardException. For the JDBC 3.0 driver, this should have the same effect as before (when it created the SQLException from the StandardException, wrapped the cause of the StandardException and chained them with setNextException()), whereas the JDBC 4.0 driver now will create the correct chain of DRDA ferry wrappers since Util.seeNextException() goes through the exception factory instead of calling setNextException() directly.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2007-05-24T21:42:12.432+0000","updated":"2007-05-24T21:42:12.432+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12499525","id":"12499525","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"Attaching a follow-up patch to address Øystein's comments. The patch removes the nextSQLException variable, adds more comments to wrapInSQLException, and also fixes some minor javadoc issues in TransactionResourceImpl.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2007-05-28T10:43:46.471+0000","updated":"2007-05-28T10:43:46.471+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12344800/comment/12499574","id":"12499574","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"Committed the follow-up patch with revision 542232.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2007-05-28T14:01:45.235+0000","updated":"2007-05-28T14:01:45.235+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1440/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06skn:"}}