{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12387765","self":"https://issues.apache.org/jira/rest/api/latest/issue/12387765","key":"DERBY-3382","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313111","id":"12313111","description":"","name":"10.4.1.3","archived":false,"released":true,"releaseDate":"2008-04-24"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2008-02-04 10:37:35.849","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"23609","customfield_12310222":"1_*:*_1_*:*_4411234198_*|*_6_*:*_1_*:*_0_*|*_5_*:*_1_*:*_86914625","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2008-03-26T11:50:57.742+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-3382/watchers","watchCount":0,"isWatching":false},"created":"2008-02-04T10:30:23.544+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"8.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313111","id":"12313111","description":"","name":"10.4.1.3","archived":false,"released":true,"releaseDate":"2008-04-24"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2008-04-01T09:45:32.094+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12312050","id":"12312050","name":"Replication"}],"timeoriginalestimate":null,"description":"If I copy the database to the slave before booting the master, slave will be out of sync with the master since new log records are created during booting.  The slave will then stop replication, but the master will not be notified.\nIf I then try to stop or failover the master the master will hang.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"39493","summary":"Replication: Slave must inform master if DBs are out of sync.","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":null,"customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":19,"total":19,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12565300","id":"12565300","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"An additional problem is that the slave does not realize that it is out of synch until the first chunk of log records is shipped. Finding out if master and slave are in synch should be part of the replication network initialization.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-02-04T10:37:35.849+0000","updated":"2008-02-04T10:37:35.849+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12566595","id":"12566595","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"Patch v1a adds a check of the log files to the replication initialization so that replication does not start if the log files are out of synch. The master will be notified whether or not the log files are synched.\r\n\r\nAll tests passed, the patch is ready for review.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-02-07T13:49:59.354+0000","updated":"2008-02-07T13:49:59.354+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12568903","id":"12568903","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"When I test this, I do not get the error message I expected on the master.  Below is an example where I do not connect to the masterDB and freeze it before it is copied.  Instead of the out-of-synch message, I get a could not establish connection message.  The slave prints the out-of-synch message.  Note also that if I try a normal connect afterwards, a first attempt to freeze the DB will fail with NPE, both a second attempt to call freeze or 'quit' will then hang.\r\n\r\nij version 10.4\r\nij> connect 'jdbc:derby:masterDB;user=oystein;password=pass;startMaster=true;slaveHost=localhost';\r\nERROR XRE04: Could not establish a connection to the peer of the replicated database 'masterDB' on address 'localhost:-1'.\r\nij> connect 'jdbc:derby:masterDB;user=oystein;password=pass';\r\nij> select sum(i), avg(i), count(*), max(i) from t;\r\n1          |2          |3          |4          \r\n-----------------------------------------------\r\n528        |16         |32         |32         \r\n\r\n1 row selected\r\nij> call syscs_util.syscs_freeze_database();\r\nERROR 38000: The exception 'java.lang.NullPointerException' was thrown while evaluating an expression.\r\nERROR XJ001: Java exception: ': java.lang.NullPointerException'.\r\nij> quit\r\n<hangs>","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-02-14T12:03:09.425+0000","updated":"2008-02-14T12:03:09.425+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12568907","id":"12568907","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Comments to the 1a patch:\r\n\r\n1. ReplicationMessageReceive#parseAndAckInstant:  No need to inform\r\n   the master in case of an unexpected message sequence?\r\n\r\n2. MasterController:  If and else parts is identical for both changes.\r\n   I guess you are supposed to use getHighestShippedInstance() for the\r\n   if-part.\r\n\r\n3. AsynchronousLogShipper:  I find the naming of\r\n   ReplicationLogBuffer#getLastInstant() a bit confusing.  I first\r\n   wondered whether it represented the last instant added to the\r\n   ReplicationLogBuffer, but I guess it is the last instant of the\r\n   first chunk of the buffer.\r\n\r\n4. LogToFile#getFlushedInstant: Looks very similar to\r\n   getFirstUnflushedInstant except it returns a long instead of a\r\n   LogCounter.  However, the names seems to indicate that they are\r\n   different.  By the way, the latter is synchronized while the former\r\n   is not.  Is there a justification for that?\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-02-14T12:17:34.301+0000","updated":"2008-02-14T12:17:34.301+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12569227","id":"12569227","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"I had a look at the NPE, which is caused by LogToFile calling masterFactory#flushedTo:\r\n\r\nLogToFile lines 3966 and on...: \r\nif (inReplicationMasterMode) {\r\n        masterFactory.flushedTo(LogCounter.\r\n                                                      makeLogInstantAsLong(fileNumber,\r\n                                                                                                  wherePosition));\r\n}\r\n\r\nSeems like LogToFile was never informed that it is no longer in replication mode :-/","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-02-15T10:39:33.330+0000","updated":"2008-02-15T10:40:15.507+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12569277","id":"12569277","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Jørgen Løland (JIRA) wrote:\r\n> Seems like LogToFile was never informed that it is no longer in replication mode :-/\r\n\r\nStrictly speaking, it has never been in replication mode since replication startup did not succeed. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-02-15T14:48:31.670+0000","updated":"2008-02-15T14:48:31.670+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12570152","id":"12570152","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"Patch 1b addresses Øysteins comments:\r\n\r\n* The out of synch error message is now displayed (no longer\r\n  wrapped in an XRE04 exception)\r\n* The NPE is removed by calling\r\n  logToFile.stopReplicationSlaveRole if startMaster fails. Also\r\n  added cleanup of the network connection if startMaster fails\r\n1 and 2: fixed\r\n3: Would getChunkLastInstant (or getChunkInstant) be more\r\n   intuitive? In that case I think we should add 'Chunk' to\r\n   getData and getSize as well. In patch 1b I only changed the\r\n   javadoc slightly.\r\n4: Good catch! I hadn't noticed that method, but I still need the\r\n   long representation. Changed name of the method to match the\r\n   existing getFirstUnflushedInstant\r\n\r\nAll tests passed.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-02-19T09:49:56.461+0000","updated":"2008-02-19T09:49:56.461+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12571408","id":"12571408","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Thanks for the follow-up patch, Jørgen.  It adresses my comments, and\r\nI have checked that the problems I reported has been fixed.  I will\r\ncommit this patch.  Some minor issues in MasterController that you may\r\nconsider for a later patch:\r\n\r\n * teardownNetwork: I am not sure this is a good name for the method\r\n   since it is actually doing more than just shutting down the network\r\n   connection.\r\n\r\n * setupConnection:  What is the point of catching StandardException\r\n   if you are just rethrowing it?\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-02-22T13:50:02.288+0000","updated":"2008-02-22T13:50:02.288+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12571409","id":"12571409","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Committed patch 1b as revision 630207.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-02-22T13:57:35.624+0000","updated":"2008-02-22T13:57:35.624+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12571410","id":"12571410","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"Hi Øystein, thanks for committing the patch.\r\n\r\nre setupConnection: it prevents the next catch (Exception) to wrap a StandardException in another StandardException","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-02-22T13:58:18.235+0000","updated":"2008-02-22T13:58:18.235+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12571412","id":"12571412","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Jørgen Løland (JIRA) wrote:\r\n> re setupConnection: it prevents the next catch (Exception) to wrap a StandardException in another StandardException\r\n\r\nAh, good point.  Objection withdrawn.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-02-22T14:07:47.511+0000","updated":"2008-02-22T14:07:47.511+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12577428","id":"12577428","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"The attached patch contains a regression test for this issue.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-03-11T12:47:28.259+0000","updated":"2008-03-11T12:47:28.259+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12578502","id":"12578502","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Thanks for the test, Jørgen.  Test case looks good, but I have a few\r\ncomments on the modifications to the framework:\r\n\r\n1. I suggest renaming slaveConnException to startSlaveException to\r\n   indicate that it is specific to startSlave command.\r\n\r\n2. slaveConnException should be set to null before starting the slave\r\n   in order to make it possible to start the slave more than once in\r\n   the same test.\r\n\r\n3. Are you sure it is a good idea to use the connection obtained when\r\n   starting the master for further operations on the master.  Would it\r\n   not be more general if it was a separate connection?  Anyhow, if\r\n   ReplicationRun is to provide the capability to use an existing\r\n   connection, I think getMasterConnection needs to be able to open a\r\n   new connection should no one exist.  (An alternative would be to\r\n   see if it was possible to let ReplicationRun extend\r\n   BaseJDBCTestCase and use its connection handling for connecting to\r\n   the master database.)\r\n\r\n4. Why do you need to copy the code from\r\n   BaseJDBCTestCase#assertSQLState? That method is static so you\r\n   should be able to use it as it is.\r\n\r\n5. assertSQLStateSlaveConn: Javadoc should state that it will wait for\r\n   some time for start slave command to complete.  Instead of \"Slave\r\n   connection attempt hangs ...\", I would prefer \"Attempt to start\r\n   slave hangs ...\", or something like that.\r\n\r\n6. If I run the replication suite with this patch from an empty\r\n   directory, it fails.  This does not happen without the patch:\r\n\r\n> java junit.textui.TestRunner -noloading org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationSuite ..java.io.IOException: Cannot run program \"/usr/local/java/jdk1.6.0_01/jre/lib/../bin/java\" (in directory \"/export/tmp/oysteing/derby-repl/testing_repl/export/tmp/oysteing/derby-repl/testing_repl/db_master\"): error=2, No such file or directory\r\n        at java.lang.ProcessBuilder.start(ProcessBuilder.java:459)\r\n        at java.lang.Runtime.exec(Runtime.java:593)\r\n        at java.lang.Runtime.exec(Runtime.java:431)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun$4.run(ReplicationRun.java:2250)\r\n        at java.lang.Thread.run(Thread.java:619)\r\nCaused by: java.io.IOException: error=2, No such file or directory\r\n        at java.lang.UNIXProcess.forkAndExec(Native Method)\r\n        at java.lang.UNIXProcess.<init>(UNIXProcess.java:53)\r\n        at java.lang.ProcessImpl.start(ProcessImpl.java:65)\r\n        at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)\r\n        ... 4 more\r\njava.lang.Exception: DRDA_NoIO.S:Could not connect to Derby Network Server on host 127.0.0.1, port 1527: Connection refused\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessageWork(NetworkServerControlImpl.java:3173)\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessage(NetworkServerControlImpl.java:1855)\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.setUpSocket(NetworkServerControlImpl.java:2497)\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.ping(NetworkServerControlImpl.java:1138)\r\n        at org.apache.derby.drda.NetworkServerControl.ping(NetworkServerControl.java:395)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.ping(ReplicationRun.java:2600)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.pingServer(ReplicationRun.java:2587)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.startServer(ReplicationRun.java:2264)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local.testLogFilesSynched(ReplicationRun_Local.java:182)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n        at java.lang.reflect.Method.invoke(Method.java:597)\r\n        at junit.framework.TestCase.runTest(TestCase.java:164)\r\n        at junit.framework.TestCase.runBare(TestCase.java:130)\r\n        at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:101)\r\n        at junit.framework.TestResult$1.protect(TestResult.java:106)\r\n        at junit.framework.TestResult.runProtected(TestResult.java:124)\r\n        at junit.framework.TestResult.run(TestResult.java:109)\r\n        at junit.framework.TestCase.run(TestCase.java:120)\r\n        at junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n        at junit.framework.TestSuite.run(TestSuite.java:225)\r\n        at junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n        at junit.framework.TestSuite.run(TestSuite.java:225)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.framework.TestResult.runProtected(TestResult.java:124)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n        at junit.framework.TestSuite.run(TestSuite.java:225)\r\n        at junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n        at junit.textui.TestRunner.start(TestRunner.java:185)\r\n        at junit.textui.TestRunner.main(TestRunner.java:143)\r\njava.io.IOException: Cannot run program \"/usr/local/java/jdk1.6.0_01/jre/lib/../bin/java\" (in directory \"/export/tmp/oysteing/derby-repl/testing_repl/export/tmp/oysteing/derby-repl/testing_repl/db_slave\"): error=2, No such file or directory        at java.lang.ProcessBuilder.start(ProcessBuilder.java:459)\r\n        at java.lang.Runtime.exec(Runtime.java:593)\r\n        at java.lang.Runtime.exec(Runtime.java:431)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun$4.run(ReplicationRun.java:2250)\r\n        at java.lang.Thread.run(Thread.java:619)\r\nCaused by: java.io.IOException: error=2, No such file or directory\r\n        at java.lang.UNIXProcess.forkAndExec(Native Method)\r\n        at java.lang.UNIXProcess.<init>(UNIXProcess.java:53)\r\n        at java.lang.ProcessImpl.start(ProcessImpl.java:65)\r\n        at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)\r\n        ... 4 more\r\njava.lang.Exception: DRDA_NoIO.S:Could not connect to Derby Network Server on host 127.0.0.1, port 4527: Connection refused\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessageWork(NetworkServerControlImpl.java:3173)\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessage(NetworkServerControlImpl.java:1855)\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.setUpSocket(NetworkServerControlImpl.java:2497)\r\n        at org.apache.derby.impl.drda.NetworkServerControlImpl.ping(NetworkServerControlImpl.java:1138)\r\n        at org.apache.derby.drda.NetworkServerControl.ping(NetworkServerControl.java:395)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.ping(ReplicationRun.java:2600)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.pingServer(ReplicationRun.java:2587)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.startServer(ReplicationRun.java:2264)\r\n        at org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local.testLogFilesSynched(ReplicationRun_Local.java:188)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n        at java.lang.reflect.Method.invoke(Method.java:597)\r\n        at junit.framework.TestCase.runTest(TestCase.java:164)\r\n        at junit.framework.TestCase.runBare(TestCase.java:130)\r\n        at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:101)\r\n        at junit.framework.TestResult$1.protect(TestResult.java:106)\r\n        at junit.framework.TestResult.runProtected(TestResult.java:124)\r\n        at junit.framework.TestResult.run(TestResult.java:109)\r\n        at junit.framework.TestCase.run(TestCase.java:120)\r\n        at junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n        at junit.framework.TestSuite.run(TestSuite.java:225)\r\n        at junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n        at junit.framework.TestSuite.run(TestSuite.java:225)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.framework.TestResult.runProtected(TestResult.java:124)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at junit.framework.TestSuite.runTest(TestSuite.java:230)\r\n        at junit.framework.TestSuite.run(TestSuite.java:225)\r\n        at junit.textui.TestRunner.doRun(TestRunner.java:121)\r\n        at junit.textui.TestRunner.start(TestRunner.java:185)\r\n        at junit.textui.TestRunner.main(TestRunner.java:143)\r\nE.^C\r\n>\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-03-13T21:38:12.050+0000","updated":"2008-03-13T21:38:12.050+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12578664","id":"12578664","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"The error reported above when running in an empty directory may not be related to this patch anyway.  I just got it on the 10.4 branch, too.  A bit strange that it disappeared when I removed this patch, though.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-03-14T09:38:46.493+0000","updated":"2008-03-14T09:38:46.493+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12580256","id":"12580256","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"Thank you for the review, Øystein. Patch 1b addresses your comments.\r\n\r\nAfter updating my sandbox, I got the same exception as you did. It turned out to be caused by another patch invalidating mine. The replication test suite completed successfully. Requesting review.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-03-19T06:58:27.331+0000","updated":"2008-03-19T06:58:27.331+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12582225","id":"12582225","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Thanks for addressing all my comments Jørgen.\r\nPatch derby-3382-test-1b.diff  committed at revision 641221.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-03-26T10:29:14.749+0000","updated":"2008-03-26T10:29:14.749+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12582250","id":"12582250","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"body":"Resolving as fixed - Issue fixed, and regression test committed.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jorgenlo","name":"jorgenlo","emailAddress":"jorgen dot loland at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Jørgen Løland","active":true},"created":"2008-03-26T11:50:57.645+0000","updated":"2008-03-26T11:50:57.645+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12584081","id":"12584081","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Test merged to the 10.4 branch at revision 641329.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-04-01T09:38:11.216+0000","updated":"2008-04-01T09:38:11.216+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12387765/comment/12584085","id":"12584085","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"body":"Reset fix version.  Bug was fixed before 10.4 release branch was created.  It was just the test patch that needed to be merged.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=oysteing","name":"oysteing","emailAddress":"oystein dot grovlen at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Øystein Grøvlen","active":true},"created":"2008-04-01T09:45:32.092+0000","updated":"2008-04-01T09:45:32.092+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-3382/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i074hj:"}}