{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12329421","self":"https://issues.apache.org/jira/rest/api/latest/issue/12329421","key":"DERBY-1047","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/11187","id":"11187","description":"","name":"10.2.1.6","archived":false,"released":true,"releaseDate":"2006-10-02"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/6","id":"6","description":"The problem isn't valid and it can't be fixed.","name":"Invalid"},"customfield_12310220":null,"customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"22281","customfield_12310222":"1_*:*_1_*:*_3812513000_*|*_6_*:*_1_*:*_0_*|*_5_*:*_1_*:*_3097000","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2006-04-10T01:14:46.000+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1047/watchers","watchCount":0,"isWatching":false},"created":"2006-02-24T22:12:53.000+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"3.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/11187","id":"11187","description":"","name":"10.2.1.6","archived":false,"released":true,"releaseDate":"2006-10-02"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2006-04-10T02:06:23.000+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[],"timeoriginalestimate":null,"description":"In checkDataSource there is a case where a statement is created outside a global transaction,\nthe global transaction is started and ended  and then the statement reused.  In this case with client we can an error \n java.sql.SQLException: 'Statement' already closed.  I will exclude this case and reference this bug number in the \ntest\n\nNote:  The server side error indicates the error occurs on session close, but I don't understand how the session is getting closed in this case.  Also the test comments say a new underlying connection is created after xa_end, but I don't know what that means with regard to the statement prepared before the global transaction started.\n \n\nThe code:\n\nPreparedStatement psParams = cs1.prepareStatement(\"select * from ru where i > ?\");\n\t\tpsParams.setCursorName(\"params\");\n\t\tpsParams.setInt(1, 2);\n\t\tresultSetQuery(\"Params-local-1\", psParams.executeQuery());\n\n\t\tsruBatch.addBatch(\"insert into ru values 4\");\n\t\tqueryOnStatement(\"sru1-local-1\", cs1, sru1);\n\t\tcs1.commit(); // need to commit to switch to an global connection;\n\t\txid = new cdsXid(1, (byte) 103, (byte) 119);\n\t\txar.start(xid, XAResource.TMNOFLAGS); // simple case - underlying connection is re-used for global.\n\t\tSystem.out.println(\"Expecting exception because global transaction sru1-global-2 is trying to use a statement with holdability true\");\n\t\tqueryOnStatement(\"sru1-global-2\", cs1, sru1);\n\t\tsruBatch.addBatch(\"insert into ru values 5\");\n\t\tStatement sru2 = cs1.createStatement();\n\t\tsru2.setCursorName(\"OAK2\");\n\t\tqueryOnStatement(\"sru2-global-3\", cs1, sru2);\n\t\tSystem.out.println(\"Expecting exception because global transaction sru1-global-4 is trying to use a statement with holdability true\");\n\t\tqueryOnStatement(\"sru1-global-4\", cs1, sru1);\n\t\tshowStatementState(\"GLOBAL \", sruState);\n\t\tshowStatementState(\"PS GLOBAL \", psruState);\n\t\tshowStatementState(\"CS GLOBAL \", csruState);\n\t\ttry {\n\t\t\tresultSetQuery(\"Params-global-1\", psParams.executeQuery());\n\t\t\tSystem.out.println(\"FAIL: should have gotten exception because holdability is true on prepared statement and that is not allowed in global transactions\");\n\t\t} catch (SQLException ex) {\n\t\t\tSystem.out.println(\"PASS: got exception because holdability is true on prepared statement and that is not allowed in global transactions\");\n\t\t\tSystem.out.println(ex.getMessage());\n\t\t}\n\n\t\txar.end(xid, XAResource.TMSUCCESS);\n\t\t// now a new underlying connection is created\n\t\tqueryOnStatement(\"sru1-local-5\", cs1, sru1);\n\t\tqueryOnStatement(\"sru2-local-6\", cs1, sru2);\n\t\tsruBatch.addBatch(\"insert into ru values 6,7\");\n\t\tStatement sru3 = cs1.createStatement();\n\t\tsru3.setCursorName(\"SF3\");\n\t\tqueryOnStatement(\"sru3-local-7\", cs1, sru3);\n\t\t// Two transactions should hold locks (global and the current XA);\n\t\tshowStatementState(\"LOCAL \", sruState);\n\t\tshowStatementState(\"PS LOCAL \", psruState);\n\t\tshowStatementState(\"CS LOCAL \", csruState);\n\t\tresultSetQuery(\"Params-local-2\", psParams.executeQuery());    /// this is the line that failes with Statement alread closed.\n\n\t\tcheckLocks(cs1);\n\t\tcs1.commit();\n\nThe client error:\n  getMaxRows() 85\njava.sql.SQLException: 'Statement' already closed.\n\tat org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:285)\n\tat org.apache.derby.client.am.PreparedStatement.executeQuery(PreparedStatement.java:301)\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.checkDataSource.runTest(checkDataSource.java:514)\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.checkDataSource.main(checkDataSource.java:133)\nCaused by: org.apache.derby.client.am.SqlException: 'Statement' already closed.\n\tat org.apache.derby.client.am.Statement.completeSqlca(Statement.java:1612)\n\tat org.apache.derby.client.am.Statement.completeOpenQuery(Statement.java:1283)\n\tat org.apache.derby.client.net.NetStatementReply.parseOpenQueryFailure(NetStatementReply.java:506)\n\tat org.apache.derby.client.net.NetStatementReply.parseOPNQRYreply(NetStatementReply.java:229)\n\tat org.apache.derby.client.net.NetStatementReply.readOpenQuery(NetStatementReply.java:59)\n\tat org.apache.derby.client.net.StatementReply.readOpenQuery(StatementReply.java:49)\n\tat org.apache.derby.client.net.NetStatement.readOpenQuery_(NetStatement.java:151)\n\tat org.apache.derby.client.am.Statement.readOpenQuery(Statement.java:1279)\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(PreparedStatement.java:1685)\n\tat org.apache.derby.client.am.PreparedStatement.executeQueryX(PreparedStatement.java:307)\n\tat org.apache.derby.client.am.PreparedStatement.executeQuery(PreparedStatement.java:292)\n\t... 2 more\njava.sql.SQLException: 'Statement' already closed.\n\tat org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:285)\n\tat org.apache.derby.client.am.PreparedStatement.executeQuery(PreparedStatement.java:301)\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.checkDataSource.runTest(checkDataSource.java:514)\n\tat org.apache.derbyTesting.functionTests.tests.jdbcapi.checkDataSource.main(checkDataSource.java:133)\nCaused by: org.apache.derby.client.am.SqlException: 'Statement' already closed.\n\tat org.apache.derby.client.am.Statement.completeSqlca(Statement.java:1612)\n\tat org.apache.derby.client.am.Statement.completeOpenQuery(Statement.java:1283)\n\tat org.apache.derby.client.net.NetStatementReply.parseOpenQueryFailure(NetStatementReply.java:506)\n\tat org.apache.derby.client.net.NetStatementReply.parseOPNQRYreply(NetStatementReply.java:229)\n\tat org.apache.derby.client.net.NetStatementReply.readOpenQuery(NetStatementReply.java:59)\n\tat org.apache.derby.client.net.StatementReply.readOpenQuery(StatementReply.java:49)\n\tat org.apache.derby.client.net.NetStatement.readOpenQuery_(NetStatement.java:151)\n\tat org.apache.derby.client.am.Statement.readOpenQuery(Statement.java:1279)\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(PreparedStatement.java:1685)\n\tat org.apache.derby.client.am.PreparedStatement.executeQueryX(PreparedStatement.java:307)\n\tat org.apache.derby.client.am.PreparedStatement.executeQuery(PreparedStatement.java:292)\n\t... 2 more\nException in thread \"main\" \n\n\nThe Server error in the derby.log\n'Statement' already closed.\n\nSQL Exception: 'Statement' already closed.\n\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:80)\n\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:87)\n\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:166)\n\n\tat org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:1919)\n\n\tat org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(ConnectionChild.java:163)\n\n\tat org.apache.derby.impl.jdbc.EmbedStatement.checkStatus(EmbedStatement.java:1247)\n\n\tat org.apache.derby.impl.jdbc.EmbedStatement.getFetchDirection(EmbedStatement.java:741)\n\n\tat org.apache.derby.iapi.jdbc.BrokeredStatement.setStatementState(BrokeredStatement.java:506)\n\n\tat org.apache.derby.iapi.jdbc.BrokeredPreparedStatement30.createDuplicateStatement(BrokeredPreparedStatement30.java:68)\n\n\tat org.apache.derby.jdbc.XAStatementControl.getRealPreparedStatement(XAStatementControl.java:127)\n\n\tat org.apache.derby.iapi.jdbc.BrokeredPreparedStatement.getPreparedStatement(BrokeredPreparedStatement.java:502)\n\n\tat org.apache.derby.iapi.jdbc.BrokeredPreparedStatement.getStatement(BrokeredPreparedStatement.java:509)\n\n\tat org.apache.derby.iapi.jdbc.BrokeredStatement.close(BrokeredStatement.java:130)\n\n\tat org.apache.derby.impl.drda.DRDAStatement.close(DRDAStatement.java:959)\n\n\tat org.apache.derby.impl.drda.Database.close(Database.java:301)\n\n\tat org.apache.derby.impl.drda.Session.close(Session.java:110)\n\n\tat org.apache.derby.impl.drda.DRDAConnThread.closeSession(DRDAConnThread.java:7106)\n\n\tat org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:251)\n\nApache Derby Network Server - 10.2.0.0 alpha shutdown at 2006-02-24 12:44:49.278 GMT\n\n\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"40767","summary":"[xa] With client xa, a PreparedStatement  created before the global transaction starts  gives  java.sql.SQLException: 'Statement' already closed.'  when used after the global transaction ends","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":5,"total":5,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12329421/comment/12373702","id":"12373702","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"I have a fix for DERBY-1047 but now the original test case no longer fails and I am having trrouble coming up with a new test case.\r\n\r\nFirstly the problem description is not really correct:\r\n\r\nThe actual problem is that  network server was closing the prepared statement if an error occurred on execution (OPNQRY) , so a subsequent execution of the prepared statement would fail.    I am attaching the  patch that fixes this issue for reference but will wait until I have a test case to commit.\r\nderby1047.patch\r\n\r\n\r\nThe reason the original repro no longer shows the issue is that  the exception that was used to invoke the issue  (using a holdable statement in a global transaction)  no longer occurs, because the fix for DERBY-1158 makes this legal.  I thought that I would change the test case to have a lock timeout instead and in fact the issue  would ocur for regular connectiosn,  but for some reason that does not seem to provoke the problem.  Attached are the old and new test cases.  \r\n Derby1047.java   - Old failing case (Doesn't fail anymore) :  run\r\n     java -Dframework=DerbyNetClient Derby1047\r\n\r\nUsePSAfterError.java - Attempt to write a new test case.\r\n    java -Dframework=DerbyNetClient UsePSAfterError\r\n\r\n     \r\nOne other interesting thing to note is that this code to close the prepared statement on statement execution error (OPNQRY error)   seems to be new to 10.2.  I do not see it in  the 10.1 codeline.  I am not sure when and why it was added.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2006-04-08T08:32:59.000+0000","updated":"2006-04-08T08:32:59.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12329421/comment/12373703","id":"12373703","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Original repro.  Doesn't actually fail anymore.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2006-04-08T08:35:01.000+0000","updated":"2006-04-08T08:35:01.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12329421/comment/12373704","id":"12373704","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"New attempt at a repro:\r\nTry to use prepared statement after lock timeout. \r\n\r\njava -Dframework=DerbyNetClient UsePSAfterError","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2006-04-08T08:36:51.000+0000","updated":"2006-04-08T08:36:51.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12329421/comment/12373705","id":"12373705","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Patch that fixes the issue, but still  need a new test case.\r\nIn DRDAConnThread.processCommands, if there was a failure executing a statement, the prepared statement would get closed.  This patch removes that code.  \r\nNote: The code to close the prepared statement after OPNQRY only exists on the trunk, not 10.1\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2006-04-08T08:41:20.000+0000","updated":"2006-04-08T08:41:20.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12329421/comment/12373782","id":"12373782","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"The core problem with the initial test case for this issue was not the problem described in the bug summary.  The 'Statement' already closed message only occurred if the had been a previous error executing the statement.  That issue has been filed and fixed as DERBY-1196, so I am closing this bug \"Invalid\".\r\n\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2006-04-10T01:14:46.000+0000","updated":"2006-04-10T01:14:46.000+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1047/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i07ccn:"}}